export const GET_NEAREST_START = 'GET_NEAREST_START';
export const GET_NEAREST_SUCCESS = 'GET_NEAREST_SUCCESS';
export const GET_NEAREST_ERROR = 'GET_NEAREST_ERROR';
export const ON_SELECT_CHANGE = 'ON_SELECT_CHANGE';
export const ADD_MARKER = 'ADD_MARKER';
export const REMOVE_MARKERS = 'REMOVE_MARKERS';
export const TOGGLE_MARKERS = 'TOGGLE_MARKERS';